Fixed path_to_parts splitter
sanic-org/sanic-routing pull request #40
Opened 2021-06-09 15:36 UTC by kserhii

This pull request fixes the `path_to_parts` helper method for such route

```python
@api.route(
    r'/image/iiif/'
    r'<image_id>/'
    r'<region:full|square|\d+,\d+,\d+,\d+>/'
    r'<size:max|\d+,|,\d+|\d+,\d+>/'
    r'<rotation:int>/'
    r'default.jpg')
```
The idea for this solution was taken from the [stackoverflow](https://stackoverflow.com/questions/732029/how-to-split-string-by-unless-is-within-brackets-using-regex) :)

2021-06-09 15:48 UTC, ahopkins commented
That is a slick solution. Will take a closer look and then also run it against the main repo. I keep meaning to add an action for that here.

2021-06-15 08:18 UTC, ahopkins commented
Might need some work on this to get all the tests passing. At least these tests on the main repo are failing:

- tests/test_routes.py:1042 test_unicode_routes
- tests/test_signals.py:13 test_add_signal
- tests/test_signals.py:22 test_add_signal_decorator
- tests/test_signals.py:53 test_dispatch_signal_triggers_multiple_handlers
- tests/test_signals.py:75 test_dispatch_signal_triggers_triggers_event
- tests/test_signals.py:110 test_dispatch_signal_triggers_with_requirements
- tests/test_signals.py:127 test_dispatch_signal_triggers_with_context
- tests/test_signals.py:142 test_dispatch_signal_triggers_with_context_fail
- tests/test_signals.py:157 test_dispatch_signal_triggers_on_bp
- tests/test_signals.py:186 test_dispatch_signal_triggers_event
- tests/test_signals.py:212 test_dispatch_signal_triggers_event_on_bp
- tests/test_signals.py:244 test_bad_finalize
- tests/test_signals.py:275 test_event_not_exist_with_autoregister
- tests/test_signals.py:284 test_dispatch_signal_triggers_non_exist_event_with_autoregister
- tests/test_signals.py:306 test_dispatch_not_exist
- tests/test_signals.py:330 test_signal_reservation[foo.bar.baz-True]
- tests/test_signals.py:330 test_signal_reservation[server.init.before-False]
- tests/test_signals.py:330 test_signal_reservation[http.request.start-False]
- tests/test_signals.py:330 test_signal_reservation[sanic.notice.anything-True]

I think the signals should be an easy fix by changing the delimiter from `.` to `\.`. But I am not sure what is going on with the unicode routes yet.

2021-06-15 16:20 UTC, kserhii commented
I was a bit confused about where those tests are. 
But then I found them in the Sanic project :)
Now, this solution should work for dot delimiter as well

2021-06-15 16:36 UTC, ahopkins commented
Great, thanks. Can you add a test in here as well with some unicode tests? The Sanic core tests use: `"/你好"`

2021-06-28 06:52 UTC, ahopkins requested changes

2021-06-28 06:52 UTC, ahopkins commented on sanic_routing/utils.py
> +            rf"{delimiter}(?=[^>]*(?:<|$))", path.lstrip(delimiter)))
```suggestion
        for part in re.split(
            rf"{delimiter}(?=[^>]*(?:<(?<!\?<)|$))", path.lstrip(delimiter)
```

2021-06-28 06:52 UTC, ahopkins commented on sanic_routing/utils.py
> +            rf"{delimiter}(?=[^>]*(?:<|$))", path.lstrip(delimiter)))
Let's expand this regex a little to allow for lookahead and lookbehind

```
/(?<=foo)bar/
/(?<!not )foo/
```

2021-06-29 22:55 UTC, kserhii commented
Done! 
Please check with Sanic tests

2021-07-01 11:09 UTC, ahopkins commented
All good :tada:

2021-07-01 11:12 UTC, ahopkins approved these changes

2021-07-01 11:29 UTC, merged